export const styleSheet={
    container:{
        display:"flex",
        flexDirection:"column",
        height:"100vh",
        width:"auto",
      backgroundColor:"#E6E7E7"
    },
    nav:{
        display:"flex",
        flexDirection:"row",
        height:"10%",
        width:"100%",
      // backgroundColor:"blue"
    },
    nav1:{
        display:"flex",
        height:"100%",
        alignItems:"center",
        justifyContent:"center",
        fontFamily:"Arial",
        width:"84%",
        backgroundColor:"#408CE2"
    },
    nav2:{
        display:"flex",
        alignItems:"center",
        justifyContent:"center",
        height:"100%%",
        width:"8%",
      // backgroundColor:"orange"
    },
    nav3:{
        display:"flex",
        alignItems:"center",
        justifyContent:"center",
        height:"100%%",
        width:"8%",
       //backgroundColor:"red"
    },
    body:{
        display:"flex",
        flexDirection:"row",
        marginTop:"90px",
        marginBottom:"30px",
        height:"100%",
        width:"100%",
   //  backgroundColor:"#E6E7E7"
    },
    img1:{
        display:"flex",
        alignItems:"center",
        justifyContent:"center",
        height:"100%",
        width:"33.3%",
       // backgroundColor:"yellow",
    },
    img2:{
        display:"flex",
        alignItems:"center",
        justifyContent:"center",
        height:"100%",
        width:"33.3%",
      //  backgroundColor:"green",
    },
    img3:{
        display:"flex",
        alignItems:"center",
        justifyContent:"center",
        height:"100%",
        width:"33.3%",
        //backgroundColor:"blue",
    },
    bottom:{
        display:"flex",
        flexDirection:"row",
        height:"100%",
        width:"100%",
       backgroundColor:"white",
    },
    descl:{
        display:"flex",
        alignItems:"center",
        justifyContent:"center",

        height:"100%",
        width:"50%",
       // backgroundColor:"blue",
    },
    descr:{
        display:"flex",
        alignItems:"center",
        justifyContent:"center",
        height:"100%",
        width:"50%",
      backgroundColor:"white",
    }

}